bot:
  prefix: "$"
  token: ""
  profile_picture: "https://i.imgur.com/Z9gqaaA.png"

guild:
  channels:
    # RSS channels
    general_rss:  000000000000000000
    google_rss:   000000000000000000
    reddit_rss:   000000000000000000
    telegram_rss: 000000000000000000
    twitter_rss:  000000000000000000
    youtube_rss:  000000000000000000

database:
  name: "watchlist.db"

reddit:
  client_id: ""
  secret: ""
  user_agent: "Pwn The Jewels - A Cyber Threat Intel Bot by Arszilla" 

twitter:
  access_token: ""
  access_token_secret: ""
  consumer_key: ""
  consumer_secret: ""

youtube:
  api_key: ""

config:
  required_keys: ['bot.token']
