bot:
  prefix: "$"
  token: ""

guild:
  id: 000000000000000000
  invite: ""

  channels:
    # RSS and Reminder channels
    general_rss:    &RSS_CHANNEL        000000000000000000
    google_rss:     &GOOGLE_RSS_CHANNEL 000000000000000000
    reddit_rss:     &REDDIT_CHANNEL     000000000000000000
    reminders:      &REMINDER_CHANNEL   000000000000000000
    telegram_rss:   &TELEGRAM_CHANNEL   000000000000000000
    twitter_rss:    &TWITTER_CHANNEL    000000000000000000
    youtube_rss:    &YOUTUBE_CHANNEL    000000000000000000

database:
  name: "watchlist.db"

reddit:
  client_id: "REDDIT_CLIENT_ID"
  secret: "REDDIT_SECRET"
  user_agent: "Pwn The Jewels - A Discord Infosec Bot by Arszilla" 

twitter:
  access_token: ""
  access_token_secret: ""
  consumer_key: ""
  consumer_secret: ""

youtube:
  api_key: ""

config:
  required_keys: ['bot.token']
