bot:
  prefix: "$"
  token: ""
  profile_picture: "https://raw.githubusercontent.com/Arszilla/Pwn-The-Jewels/master/images/Pwn%20The%20Jewels.png"

guild:
  channels:
    # RSS and Reminder channels
    general_rss:  000000000000000000
    google_rss:   000000000000000000
    reddit_rss:   000000000000000000
    telegram_rss: 000000000000000000
    twitter_rss:  000000000000000000
    youtube_rss:  000000000000000000

database:
  name: "watchlist.db"

reddit:
  client_id: "REDDIT_CLIENT_ID"
  secret: "REDDIT_SECRET"
  user_agent: "Pwn The Jewels - A Discord Infosec Bot by Arszilla" 

twitter:
  access_token: ""
  access_token_secret: ""
  consumer_key: ""
  consumer_secret: ""

youtube:
  api_key: ""

config:
  required_keys: ['bot.token']
